### ISSUE TITLE
Gambling todo

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/BattleRoyaleIssues#100]
- [x] Give players coins initially (code ready)
- [x] Give players skins initially
- [x] Fix hints calling weapons nil
- [x] Make sure skins work when spectating
- [x] Update roulette menu
- [x] Update skin weights, remove/make gold more rare
- [x] Add valentines skin
- [x] ~~Make sure skins persist when dropping and another player picking the weapon up~~
