### ISSUE TITLE
Reporter todo

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/BattleRoyaleIssues#181]
- [x] Discord notification on new report
- [ ] Better UX for reporting, easier to find it
- [ ] Admin addon for viewing reports
